### ISSUE TITLE
Can't use EnvCreateFlags

### ISSUE THREAD

**Issue by krakatoa** [vhbit/lmdb-rs#18]
Hey! I have the following issue, when trying to create an environment with EnvCreateFlags, I get this error:
```
thread '<main>' panicked at 'error opening environment: 22: Invalid argument', src/main.rs:38
An unknown error occurred
```
Code extract is:
```rust
use lmdb::core::{EnvCreateReadOnly};
let env_builder = EnvBuilder::new() 
  .map_size(256 * 1024 * 1024)      
  .max_dbs(5)                       
  .flags(EnvCreateReadOnly);        
let env = env_builder.open(&path, 0o664).unwrap();
```
Do you find anything wrong with that ?
Thanks !

Btw, great lib! I tried to discover the issue by myself but I'm still learning Rust :)

**Comment by vhbit** [comment]
hmm, that's weird, are you sure that environment already exists in that path before you open it as read-only?

**Comment by xitep** [comment]
I remember I encountered this as well once, but was not following up on a fix :/

I think the errors comes from the invocation of [mdb_env_set_flags](https://github.com/LMDB/lmdb/blob/56e4e20ebca0ae6459c479de66cd174c10d2d4c6/libraries/liblmdb/mdb.c#L8956) in [EnvBuilder#open](https://github.com/vhbit/lmdb-rs/blob/master/src/core.rs#L567) since the "read only" flag is not [CHANGEABLE](https://github.com/LMDB/lmdb/blob/56e4e20ebca0ae6459c479de66cd174c10d2d4c6/libraries/liblmdb/mdb.c#L4516).

**Comment by vhbit** [comment]
@xitep aha, thanks for a hint!

**Comment by xitep** [comment]
i had an hour to play with the new change and unfortunately still fail to iterate/read a "read-only" database :( here's a complete program to demonstrate the problem:

```
extern crate lmdb_rs as lmdb;

use std::path::Path;
use std::env;

fn main() {
    let dbpath: String = env::args().skip(1).next().unwrap();
    let dbpath = Path::new(&dbpath);
    if let Err(e) = test(&dbpath) {
        println!("Error: {}", e);
    }
}

fn test(path: &Path) -> Result<(), lmdb::MdbError> {
    let env = try!(lmdb::EnvBuilder::new()
                   .flags(lmdb::core::EnvCreateReadOnly
                          | lmdb::core::EnvCreateNoLock
                          | lmdb::core::EnvCreateNoMemInit
                          | lmdb::core::EnvCreateNoMetaSync)
                   .autocreate_dir(false)
                   .open(&path, 0));
    let dbh = try!(env.get_default_db(lmdb::DbFlags::empty()));
    let mut tx = try!(env.get_reader());
    {
        let db = tx.bind(&dbh);
        for c in try!(db.iter()) {
            let key: &str = c.get_key();
            let val: &str = c.get_value();
            println!("{}: {}", key, val);
        }
    }
    tx.abort();
    Ok(())
}
```

this time, the culprit seems to be [the call to create_transaction in Environment#_open_db](https://github.com/vhbit/lmdb-rs/blob/master/src/core.rs#L800).  when I specify `ffi::MDB_RDONLY` as the `flags` argument (just have hard-coded it in lmdb-rs and recompiled) the program finally succeeded. (with this fix the above program works even if the database is not owned by the user who runs the program.)

unfortunately, right now i lack the time to fix this myself. i would propose to re-open this ticket until we get this handled. what do you think @vhbit ?

**Comment by vhbit** [comment]
@xitep yep, reopening, will check for a workaround later.

**Comment by xitep** [comment]
@vhbit may i ask you to have a look at [this commit in my fork](https://github.com/xitep/lmdb-rs/commit/63bda9ca297505f32d574af95690b98e8ae80245) ... it looks like this could be a start on the problem. but ...

1. i'm not sure about thread-safety (`Sync`, `Send`) around the `Environment#read_only` field (haven't gotten to that topic in rust yet).
2. in some places (e.g. opening a read/write transaction) we could provide a custom error message when trying to modify a read_only database/environment

**Comment by vhbit** [comment]
@xitep looks good

> i'm not sure about thread-safety (Sync, Send) around the Environment#read_only field (haven't gotten to that topic in rust yet).

that shouldn't be a problem at all in this case

> in some places (e.g. opening a read/write transaction) we could provide a custom error message when trying to modify a read_only database/environment

yep, although it can be tricky. I think that for starters `new_transaction`  can return an `MdbError` if environment is read-only, but more sophisticated checks like while writing through a bound database can be added later and probably can even use some type chemistry to do it at compile time.

also it would be great to add the test above to `test_readonly_env` in `src/tests.rs`

**Comment by xitep** [comment]
many thanks for your guidance @vhbit. with #19 i added the test (there were no more changes to the commit in `core.rs` of mine you already reviewed). regarding `MdbError` I agree and especially like the thought of having the erroneous situation prevented by an appropriate API.

**Comment by vhbit** [comment]
@krakatoa I think with latest @xitep changes this issue should be solved in most cases.

**Comment by krakatoa** [comment]
@vhbit @xitep thanks you, It works perfectly :+1: !
